language: php

php:
  - 5.5
  - 5.6
  - 7.0

services:
  - mysql

before_script:
  - phpenv config-add travis_php.ini
  - mysql < tests/setup.sql
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --bootstrap autoload.php tests
